# Generated by Django 4.0.2 on 2022-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_social', '0002_user_bio_user_followers_user_following_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='avtar.png', upload_to='profile'),
        ),
    ]
