# Generated by Django 4.0.2 on 2022-04-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_social', '0003_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
