# Generated by Django 4.0.2 on 2022-04-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_social', '0004_user_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('private_status', models.BooleanField(default=False)),
                ('hashtag', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='posts')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='user_social.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_social.user')),
            ],
        ),
    ]
