# Generated by Django 4.0.2 on 2022-04-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_social', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
