# Generated by Django 4.0.2 on 2022-04-15 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_social', '0007_post_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_whom', to='user_social.user')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_follows', to='user_social.user')),
            ],
        ),
    ]
